### ISSUE TITLE
Wisps Fill Mobcap

### ISSUE THREAD

**Issue by Devan-Kerman** [wisp-forest/affinity#18]
The wisps don't despawn (or they spawn to frequently?) and fill the mobcap very quickly, preventing any more mobs from spawning.

**Comment by gliscowo** [comment]
While this is indeed an issue in release builds, I've made a number of adjustments to the Wisp spawning and despawning mechanics that are yet to be released which should completely alleviate this problem. If it's not too much hassle, could you try compiling an up-to-date build of the 1.20.4 branch and verifying that the issue is resolved?

**Comment by Devan-Kerman** [comment]
Our server is on 1.20.1 unfortunately, though I can try and check for you in a bit

**Comment by gliscowo** [comment]
From our own experience with these changes I'll assume that this issue is fixed - please reopen it if that is not the case
Cheers
