### ISSUE TITLE
[Feature] Do you consider the support of multiple languages ​​in the book?

### ISSUE THREAD

**Issue by SanQianQVQ** [wisp-forest/affinity#26]
I noticed that although there is a lang folder, it seems that the tutorial part depends on the Markdown file. Do these Markdown also provide multi -language plans (or make it translate)?

**Comment by gliscowo** [comment]
Lavender does indeed fully support translations - in order to do so, the same folder structure which is found in `assets/affinity/lavender/entries/wispen_testament` must be replicated in (for example) `assets/affinity/lavender/entries/wispen_testament/de_de`.

For instance, to translate the Affine Candle entry to German, you'd add `assets/affinity/lavender/entries/wispen_testament/de_de/affine_candle.md` - this would then override its top-level equivalent when German language is selected in-game.

Cheers
